// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloworldClient is the client API for Helloworld service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloworldClient interface {
	CreateHelloworld(ctx context.Context, in *CreateHelloworldRequest, opts ...grpc.CallOption) (*CreateHelloworldReply, error)
	UpdateHelloworld(ctx context.Context, in *UpdateHelloworldRequest, opts ...grpc.CallOption) (*UpdateHelloworldReply, error)
	DeleteHelloworld(ctx context.Context, in *DeleteHelloworldRequest, opts ...grpc.CallOption) (*DeleteHelloworldReply, error)
	GetHelloworld(ctx context.Context, in *GetHelloworldRequest, opts ...grpc.CallOption) (*GetHelloworldReply, error)
	ListHelloworld(ctx context.Context, in *ListHelloworldRequest, opts ...grpc.CallOption) (*ListHelloworldReply, error)
}

type helloworldClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloworldClient(cc grpc.ClientConnInterface) HelloworldClient {
	return &helloworldClient{cc}
}

func (c *helloworldClient) CreateHelloworld(ctx context.Context, in *CreateHelloworldRequest, opts ...grpc.CallOption) (*CreateHelloworldReply, error) {
	out := new(CreateHelloworldReply)
	err := c.cc.Invoke(ctx, "/api.helloworld.Helloworld/CreateHelloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloworldClient) UpdateHelloworld(ctx context.Context, in *UpdateHelloworldRequest, opts ...grpc.CallOption) (*UpdateHelloworldReply, error) {
	out := new(UpdateHelloworldReply)
	err := c.cc.Invoke(ctx, "/api.helloworld.Helloworld/UpdateHelloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloworldClient) DeleteHelloworld(ctx context.Context, in *DeleteHelloworldRequest, opts ...grpc.CallOption) (*DeleteHelloworldReply, error) {
	out := new(DeleteHelloworldReply)
	err := c.cc.Invoke(ctx, "/api.helloworld.Helloworld/DeleteHelloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloworldClient) GetHelloworld(ctx context.Context, in *GetHelloworldRequest, opts ...grpc.CallOption) (*GetHelloworldReply, error) {
	out := new(GetHelloworldReply)
	err := c.cc.Invoke(ctx, "/api.helloworld.Helloworld/GetHelloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloworldClient) ListHelloworld(ctx context.Context, in *ListHelloworldRequest, opts ...grpc.CallOption) (*ListHelloworldReply, error) {
	out := new(ListHelloworldReply)
	err := c.cc.Invoke(ctx, "/api.helloworld.Helloworld/ListHelloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloworldServer is the server API for Helloworld service.
// All implementations must embed UnimplementedHelloworldServer
// for forward compatibility
type HelloworldServer interface {
	CreateHelloworld(context.Context, *CreateHelloworldRequest) (*CreateHelloworldReply, error)
	UpdateHelloworld(context.Context, *UpdateHelloworldRequest) (*UpdateHelloworldReply, error)
	DeleteHelloworld(context.Context, *DeleteHelloworldRequest) (*DeleteHelloworldReply, error)
	GetHelloworld(context.Context, *GetHelloworldRequest) (*GetHelloworldReply, error)
	ListHelloworld(context.Context, *ListHelloworldRequest) (*ListHelloworldReply, error)
	mustEmbedUnimplementedHelloworldServer()
}

// UnimplementedHelloworldServer must be embedded to have forward compatible implementations.
type UnimplementedHelloworldServer struct {
}

func (UnimplementedHelloworldServer) CreateHelloworld(context.Context, *CreateHelloworldRequest) (*CreateHelloworldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHelloworld not implemented")
}
func (UnimplementedHelloworldServer) UpdateHelloworld(context.Context, *UpdateHelloworldRequest) (*UpdateHelloworldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHelloworld not implemented")
}
func (UnimplementedHelloworldServer) DeleteHelloworld(context.Context, *DeleteHelloworldRequest) (*DeleteHelloworldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHelloworld not implemented")
}
func (UnimplementedHelloworldServer) GetHelloworld(context.Context, *GetHelloworldRequest) (*GetHelloworldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHelloworld not implemented")
}
func (UnimplementedHelloworldServer) ListHelloworld(context.Context, *ListHelloworldRequest) (*ListHelloworldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHelloworld not implemented")
}
func (UnimplementedHelloworldServer) mustEmbedUnimplementedHelloworldServer() {}

// UnsafeHelloworldServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloworldServer will
// result in compilation errors.
type UnsafeHelloworldServer interface {
	mustEmbedUnimplementedHelloworldServer()
}

func RegisterHelloworldServer(s grpc.ServiceRegistrar, srv HelloworldServer) {
	s.RegisterService(&Helloworld_ServiceDesc, srv)
}

func _Helloworld_CreateHelloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHelloworldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloworldServer).CreateHelloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.helloworld.Helloworld/CreateHelloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloworldServer).CreateHelloworld(ctx, req.(*CreateHelloworldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helloworld_UpdateHelloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHelloworldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloworldServer).UpdateHelloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.helloworld.Helloworld/UpdateHelloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloworldServer).UpdateHelloworld(ctx, req.(*UpdateHelloworldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helloworld_DeleteHelloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHelloworldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloworldServer).DeleteHelloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.helloworld.Helloworld/DeleteHelloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloworldServer).DeleteHelloworld(ctx, req.(*DeleteHelloworldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helloworld_GetHelloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHelloworldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloworldServer).GetHelloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.helloworld.Helloworld/GetHelloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloworldServer).GetHelloworld(ctx, req.(*GetHelloworldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helloworld_ListHelloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHelloworldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloworldServer).ListHelloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.helloworld.Helloworld/ListHelloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloworldServer).ListHelloworld(ctx, req.(*ListHelloworldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Helloworld_ServiceDesc is the grpc.ServiceDesc for Helloworld service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Helloworld_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.helloworld.Helloworld",
	HandlerType: (*HelloworldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHelloworld",
			Handler:    _Helloworld_CreateHelloworld_Handler,
		},
		{
			MethodName: "UpdateHelloworld",
			Handler:    _Helloworld_UpdateHelloworld_Handler,
		},
		{
			MethodName: "DeleteHelloworld",
			Handler:    _Helloworld_DeleteHelloworld_Handler,
		},
		{
			MethodName: "GetHelloworld",
			Handler:    _Helloworld_GetHelloworld_Handler,
		},
		{
			MethodName: "ListHelloworld",
			Handler:    _Helloworld_ListHelloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
